"""Render decisions database to docs/decisions.md at the project's git root."""

import sqlite3
import subprocess
from pathlib import Path


def _get_git_root() -> Path | None:
    """Return the git root directory, or None if not in a git repo."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return Path(result.stdout.strip())
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def render_decisions_md(conn: sqlite3.Connection) -> str:
    """Generate markdown string from all decisions in the database."""
    rows = conn.execute(
        "SELECT id, title, status, tags, created_at, updated_at, "
        "context, alternatives, consequences, superseded_by "
        "FROM decisions ORDER BY id"
    ).fetchall()

    if not rows:
        return (
            "# Decision Records\n\n"
            "*Auto-generated by mc-tool-decisions. Do not edit manually.*\n\n"
            "No decisions recorded yet.\n"
        )

    lines = [
        "# Decision Records\n",
        "*Auto-generated by mc-tool-decisions. Do not edit manually.*\n",
        "| # | Decision | Status | Tags | Date |",
        "|---|----------|--------|------|------|",
    ]

    for row in rows:
        did, title, status, tags, created_at, *_ = row
        date = created_at[:10] if created_at else ""
        tags_str = tags or ""
        display_title = title
        if status in ("superseded", "deprecated"):
            display_title = f"~~{title}~~"
        lines.append(f"| {did} | {display_title} | {status} | {tags_str} | {date} |")

    lines.append("")

    for row in rows:
        (
            did,
            title,
            status,
            tags,
            created_at,
            updated_at,
            context,
            alternatives,
            consequences,
            superseded_by,
        ) = row

        lines.append("---")
        lines.append("")
        lines.append(f"## DR-{did}: {title}")
        lines.append("")

        meta = f"**Status:** {status}"
        if tags:
            meta += f" | **Tags:** {tags}"
        lines.append(meta)

        date_line = f"**Recorded:** {created_at[:10]}" if created_at else ""
        if updated_at:
            date_line += f" | **Updated:** {updated_at[:10]}"
        if date_line:
            lines.append(date_line)

        if superseded_by:
            lines.append(f"**Superseded by:** DR-{superseded_by}")

        lines.append("")

        if context:
            lines.append("### Context")
            lines.append(context)
            lines.append("")

        if alternatives:
            lines.append("### Alternatives considered")
            lines.append(alternatives)
            lines.append("")

        if consequences:
            lines.append("### Consequences")
            lines.append(consequences)
            lines.append("")

    return "\n".join(lines)


def write_decisions_md(conn: sqlite3.Connection) -> None:
    """Write docs/decisions.md at the git root. Skips silently if not in a git repo."""
    git_root = _get_git_root()
    if git_root is None:
        return

    docs_dir = git_root / "docs"
    docs_dir.mkdir(exist_ok=True)

    content = render_decisions_md(conn)
    (docs_dir / "decisions.md").write_text(content)
