"""Generate ``docs/reference/**/*.md`` from each module's ``__all__``.

Run from the repo root before ``mkdocs build``:

    uv run python docs/gen_ref_pages.py

For every entry in :data:`REFERENCE_MODULES` (grouped by section —
Core, Tools, Hooks — each a list of ``(dotted_name, display)`` pairs):

  1. Locate the source file: package ``__init__.py`` if the entry is a
     package, otherwise the single-file module.
  2. Parse ``__all__`` from the source.
  3. Scan the source text for ``# Section`` comments interleaved inside
     the ``__all__`` list — those become H2 headings on the reference
     page.
  4. Write the reference page at a nested path mirroring the dotted
     name. ``context`` lands at ``reference/context.md``;
     ``tools.memory`` lands at ``reference/tools/memory.md`` so the
     URL becomes ``/reference/tools/memory/``.

A short ``docs/reference/index.md`` is regenerated alongside, grouped
by the same Core/Tools/Hooks sections that define the data.

Contract: every module listed must export ``__all__``. A missing one
raises — the generator will not silently under-document.

CI integration: ``--check`` exits non-zero if any generated file
differs from what is checked in. That is the drift detector — the
nav lives in ``mkdocs.yml``, but the per-module reference pages are
authored here.

Adapted from cairn's ``docs/gen_ref_pages.py``; the mait-code specific
changes are the namespace, the grouped module structure, dotted-name
path resolution, and nested output filenames.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src" / "mait_code"
OUT_ROOT = REPO_ROOT / "docs" / "reference"

REFERENCE_MODULES: dict[str, list[tuple[str, str]]] = {
    "Core": [
        ("context", "Context"),
        ("cli", "CLI"),
        ("config", "Configuration"),
        ("llm", "LLM"),
        ("logging", "Logging"),
        ("ssl", "SSL"),
    ],
    "Tools": [
        ("tools.memory", "Memory"),
        ("tools.reminders", "Reminders"),
        ("tools.tasks", "Tasks"),
        ("tools.board", "Board"),
        ("tools.inbox", "Inbox"),
        ("tools.decisions", "Decisions"),
        ("tools.web_fetch", "Web fetch"),
    ],
    "Hooks": [
        ("hooks.observe", "Observe"),
        ("hooks.session_start", "Session start"),
        ("hooks.auto_format", "Auto-format"),
    ],
}

GENERATED_BANNER = (
    "<!-- Generated by docs/gen_ref_pages.py from each module's __all__.\n"
    "     Do not edit by hand — re-run the generator instead. -->\n"
)


class Section(NamedTuple):
    heading: str | None
    symbols: list[str]


def _source_path(name: str) -> Path:
    """Resolve a (possibly dotted) module name to its source file.

    Args:
        name: Module name relative to ``mait_code``, e.g. ``"context"``
            or ``"tools.memory"``.

    Returns:
        The path to the package ``__init__.py`` or the single-file
        module.

    Raises:
        FileNotFoundError: If neither a package nor a module file exists
            at the resolved location.
    """
    parts = name.split(".")
    pkg = SRC_ROOT.joinpath(*parts) / "__init__.py"
    if pkg.exists():
        return pkg
    if len(parts) == 1:
        mod = SRC_ROOT / f"{parts[0]}.py"
    else:
        mod = SRC_ROOT.joinpath(*parts[:-1]) / f"{parts[-1]}.py"
    if mod.exists():
        return mod
    raise FileNotFoundError(f"No package or module found for mait_code.{name}")


def _output_path(name: str) -> Path:
    """Return the output reference page path for a module name.

    Dotted module names become nested directory paths so the URL
    mirrors the dotted hierarchy — ``tools.memory`` writes to
    ``docs/reference/tools/memory.md`` and renders at
    ``/reference/tools/memory/``.
    """
    parts = name.split(".")
    return OUT_ROOT.joinpath(*parts[:-1]) / f"{parts[-1]}.md"


def _parse_all(source: str, path: Path) -> list[str]:
    """Parse the ``__all__`` literal from a module source.

    Args:
        source: Raw source text of the module.
        path: Path to the source, used for error messages.

    Returns:
        The list of exported symbol names in source order.

    Raises:
        ValueError: If ``__all__`` is missing or not a list/tuple of
            string literals.
    """
    tree = ast.parse(source, filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id == "__all__":
                value = node.value
                if not isinstance(value, ast.List | ast.Tuple):
                    raise ValueError(f"{path}: __all__ must be a list or tuple literal")
                names: list[str] = []
                for elt in value.elts:
                    if not isinstance(elt, ast.Constant) or not isinstance(elt.value, str):
                        raise ValueError(f"{path}: __all__ must contain string literals only")
                    names.append(elt.value)
                return names
    raise ValueError(f"{path}: missing __all__ — required for auto-reference")


_ALL_START_RE = re.compile(r"^__all__\s*=\s*[\[(]")
_ALL_END_RE = re.compile(r"^[\])]")
_SECTION_RE = re.compile(r"^\s*#\s*(.+?)\s*$")
_SYMBOL_RE = re.compile(r"^\s*[\"']([^\"']+)[\"']\s*,?\s*$")


def _parse_sections(source: str, known: list[str]) -> list[Section]:
    """Walk the ``__all__`` block line by line; group symbols by ``# Section`` comments.

    Args:
        source: Raw source text of the module.
        known: The set of symbol names parsed via AST — used to filter
            out unrelated lines inside the ``__all__`` block.

    Returns:
        A list of :class:`Section` records preserving source order. If
        no ``# Section`` comment is found, a single un-headed section
        containing every symbol is returned.
    """
    in_block = False
    current_heading: str | None = None
    buckets: list[Section] = []
    current: list[str] = []

    for line in source.splitlines():
        if not in_block:
            if _ALL_START_RE.match(line):
                in_block = True
            continue
        if _ALL_END_RE.match(line):
            break
        section_match = _SECTION_RE.match(line)
        if section_match:
            if current:
                buckets.append(Section(current_heading, current))
                current = []
            current_heading = section_match.group(1)
            continue
        symbol_match = _SYMBOL_RE.match(line)
        if symbol_match and symbol_match.group(1) in known:
            current.append(symbol_match.group(1))

    if current:
        buckets.append(Section(current_heading, current))

    if not buckets:
        buckets = [Section(None, list(known))]

    return buckets


def _render_module(name: str, display: str, sections: list[Section]) -> str:
    """Render a single reference page.

    Args:
        name: Dotted module name relative to ``mait_code``.
        display: Human-readable page title.
        sections: Parsed sections from :func:`_parse_sections`.

    Returns:
        The full Markdown content of the page, including the generated
        banner.
    """
    lines: list[str] = [GENERATED_BANNER, f"# {display} — API reference", ""]
    for section in sections:
        if section.heading:
            lines.append(f"## {section.heading}")
            lines.append("")
        for symbol in section.symbols:
            lines.append(f"::: mait_code.{name}.{symbol}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _index_link(name: str) -> str:
    """Return the relative link from ``reference/index.md`` to a module page.

    For ``tools.memory`` (file at ``reference/tools/memory.md``), the
    index sits in the same root, so the link is ``tools/memory.md``.
    """
    return f"{name.replace('.', '/')}.md"


def _render_index() -> str:
    """Render ``docs/reference/index.md`` with H2 groups per section."""
    lines: list[str] = [
        GENERATED_BANNER,
        "# API reference",
        "",
        "Auto-generated from each module's ``__all__``. Pages are grouped",
        "by the ``# Section`` comments inside ``__all__``, so editorial",
        "structure lives next to the code rather than in hand-curated",
        "reference pages.",
        "",
        "Contributors: see the",
        "[contributing-docs guide](../contributing-docs.md) and",
        "`docs/gen_ref_pages.py` for the regeneration workflow.",
        "",
    ]
    for group, modules in REFERENCE_MODULES.items():
        lines.append(f"## {group}")
        lines.append("")
        for name, display in modules:
            lines.append(f"- [{display}]({_index_link(name)}) — `mait_code.{name}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _build() -> dict[Path, str]:
    """Build every reference page in memory.

    Returns:
        A mapping of output path to rendered Markdown content, for the
        twelve module pages plus the index.
    """
    artefacts: dict[Path, str] = {}
    for modules in REFERENCE_MODULES.values():
        for name, display in modules:
            path = _source_path(name)
            source = path.read_text(encoding="utf-8")
            names = _parse_all(source, path)
            sections = _parse_sections(source, names)
            artefacts[_output_path(name)] = _render_module(name, display, sections)
    artefacts[OUT_ROOT / "index.md"] = _render_index()
    return artefacts


def main(argv: list[str] | None = None) -> int:
    """Generate every reference page, or check for drift.

    Args:
        argv: Optional argument list (defaults to ``sys.argv[1:]``).

    Returns:
        ``0`` on success. ``1`` when ``--check`` finds a generated
        file that differs from what is checked in.
    """
    parser = argparse.ArgumentParser(description="Generate docs/reference/*.md from __all__.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any file would change. Use in CI to detect drift.",
    )
    args = parser.parse_args(argv)

    artefacts = _build()
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    drift: list[Path] = []
    for out_path, content in artefacts.items():
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None
        if existing == content:
            continue
        if args.check:
            drift.append(out_path)
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content, encoding="utf-8")

    if args.check:
        if drift:
            print("Reference docs are out of date. Re-run: uv run python docs/gen_ref_pages.py")
            for path in drift:
                print(f"  - {path.relative_to(REPO_ROOT)}")
            return 1
        return 0

    print(f"Wrote {len(artefacts)} reference pages under {OUT_ROOT.relative_to(REPO_ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
